<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DeleteAndUpdateFilmDb.aspx.cs" Inherits="DeleteAndUpdateFilmDb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
      <center>
          <%Response.Write("<center><h1>Film database - update and delete</h1></center>");%>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" DataKeyNames="Film_ID">
            <Columns>
                <asp:BoundField DataField="Film_ID" HeaderText="Film_ID" SortExpression="Film_ID" ReadOnly="True" />
                <asp:BoundField DataField="IsFilmFree" HeaderText="IsFilmFree" SortExpression="IsFilmFree" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT Film_ID, IsFilmFree FROM Film" 
            UpdateCommand="UPDATE Film SET IsFilmFree = @IsFilmFree WHERE (Film_ID = @Film_ID)"
            DeleteCommand="DELETE FROM Film WHERE (IsFilmFree = '0')">
            <UpdateParameters>
                <asp:Parameter Name="IsFilmFree" />
                <asp:Parameter Name="Film_ID" />
            </UpdateParameters>
          </asp:SqlDataSource>
         
      </center>   
    </div>
    </form>
</body>
</html>
